accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    
	path("home/", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    
   	path('reset_password/',
	auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html",email_template_name = 'accounts/password_reset_email.html'),
	name="password_reset"),

    path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
    name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
    name="password_reset_confirm"),

    path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
    name="password_reset_complete"),

    path('therapist_signup/',views.therapist_signup,name="therapist_signup")

]

community_forum/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
app_name="community_forum"
urlpatterns=[
	path('',views.CategoryView.as_view()),
	path('quiz/',views.QuizView,name="quiz"),
	path('<str:category>/',views.SubforumView,name="subforum"),
	path('<int:pk>/info/',views.CategoryInfo,name="categoryInfo"),
	path('<str:category>/questions/new/',views.NewQuestionView.as_view()),
	path('questions/<int:pk>/',views.QuestionView.as_view(),name="question-detail"),
	path('questions/<int:pk>/answer/',views.AnswerView.as_view(),name="answer-detail"),
	path('up_vote/<int:pk>/',views.QuestionUpVoteView,name="up_vote"),
	path('down_vote/<int:pk>/',views.QuestionDownVoteView,name="down_vote"),
	path('answer_up_vote/<int:pk>/<int:pk_alt>',views.AnswerUpVoteView,name="answer_up_vote"),
	path('answer_down_vote/<int:pk>/<int:pk_alt>',views.AnswerDownVoteView,name="answer_down_vote"),
]

safe_space/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('ask_the_doctor/',include('Ask_the_doctor.urls')),
    path('community_forum/',include('community_forum.urls')),
    path('profile/',include('user_profile.urls')),
    path('therapist_dashboard/',include('therapist_dashboard.urls')),
    path('private_chats/',include('private_chats.urls')),
]

community_forum/models.py
from django.db import models
from ckeditor.fields import RichTextField
from accounts.models import Profile
# Create your models here.
class Categories(models.Model):
	class Meta:
		verbose_name_plural="Categories"

	id=models.AutoField(primary_key=True,unique=True)
	category_name=models.CharField(max_length=200,blank=True)

	def __str__(self):
		return f"{self.category_name}"


class Questions(models.Model):
	class Meta:
		verbose_name_plural="Questions"

	id=models.AutoField(primary_key=True,unique=True)
	user=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='questions',blank=True,null=True)
	category=models.ForeignKey(Categories,on_delete=models.CASCADE,related_name='questions',blank=True,null=True)
	question_title=models.CharField(max_length=300,blank=True,null=True)
	question_detail=RichTextField(blank=True,null=True)
	up_votes=models.ManyToManyField(Profile,related_name='questions_up_votes')
	down_votes=models.ManyToManyField(Profile,related_name='questions_down_votes')
	date=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.question_title}"

	def total_upvotes(self):
		return self.up_votes.count()
	def total_downvotes(self):
		return self.down_votes.count()

'''class QuestionVotes(models.Model):
	class Meta:
		verbose_name_plural= "Question Votes"

	id=models.AutoField(primary_key=True,unique=True)
	user=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='questionvotes',blank=True,null=True)
	question=models.ForeignKey(Questions,on_delete=models.CASCADE,related_name='questionvotes',blank=True,null=True)
	up_votes=models.IntegerField(blank=True)
	down_votes=models.IntegerField(blank=True)

	def __str__(self):
		return f"{self.id}"
'''

class Answers(models.Model):
	class Meta:
		verbose_name_plural="Answers"

	id=models.AutoField(primary_key=True,unique=True)
	user=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='answers',blank=True,null=True)
	category=models.ForeignKey(Categories,on_delete=models.CASCADE,related_name='answers',blank=True,null=True)
	question=models.ForeignKey(Questions,on_delete=models.CASCADE,related_name='answers',blank=True,null=True)
	answer=RichTextField(blank=True,null=True)
	up_votes=models.ManyToManyField(Profile,related_name='answers_up_votes')
	down_votes=models.ManyToManyField(Profile,related_name='answers_down_votes')
	date=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.id}"

	def total_upvotes(self):
		return self.up_votes.count()
	def total_downvotes(self):
		return self.down_votes.count()


'''class AnswerVotes(models.Model):
	class Meta:
		verbose_name_plural="Answer Votes"

	id=models.AutoField(primary_key=True,unique=True)
	user=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='answervotes',blank=True,null=True)
	answer=models.ForeignKey(Answers,on_delete=models.CASCADE,related_name='answervotes',blank=True,null=True)
	up_votes=models.IntegerField(blank=True)
	down_votes=models.IntegerField(blank=True)

	def __str__(self):
		return f"{self.id}"
'''

'''class Comments(models.Model):
	class Meta:
		verbose_name_plural="Comments"

	id=models.AutoField(primary_key=True,unique=True)
	user=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='Comments',blank=True,null=True)
	question=models.ForeignKey(Questions,on_delete=models.CASCADE,related_name='Comments',blank=True,null=True)
	comment=RichTextField(blank=True,null=True)
	date=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.id}"
'''

community_forum/forms.py
from django import forms
from django.forms import ModelForm
from .models import Answers,Questions
from ckeditor.widgets import CKEditorWidget
class AnswerForm(forms.ModelForm):

   
	answer=forms.CharField(widget=CKEditorWidget(attrs={'class': 'form-control','placeholder': 'Type here'}))

	class Meta:
		model=Answers
		fields=['answer']
		
   
class QuestionForm(forms.ModelForm):
	question_title=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Give a title to your question'}))
	question_detail=forms.CharField(widget=CKEditorWidget(attrs={'class': 'form-control','placeholder': 'Type here'}))
	class Meta:
		model=Questions
		fields=['question_title','question_detail']

class AnswerUpdateForm(forms.ModelForm):
	answer=forms.CharField(widget=CKEditorWidget(attrs={'class':'form-control','placeholder':'Type here'}))
	class Meta:
		model=Answers
		fields=['answer']

community_forum/views.py
from django.shortcuts import render,redirect
from community_forum.models import Categories
from django.http import HttpResponse,HttpResponseRedirect
from django.views import View
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from .forms import AnswerForm,QuestionForm
from community_forum.models import Questions,Answers
from django.urls import reverse
from django.core.mail import send_mail,EmailMultiAlternatives
from django.conf import settings
from django.template.loader import get_template


# Create your views here.
class CategoryView(View):

	def get(self, request, *args, **kwargs):

		categories=Categories.objects.order_by('category_name')
		context={
			'categories':categories
		}
		return render(request,'community_forum/categories.html',context)
def QuizView(request,*args,**kwargs):
	context={}
	return render(request,'community_forum/quiz.html',context)

def SubforumView(request,*args,**kwargs):
	category=kwargs['category']
	category_=get_object_or_404(Categories,category_name=category)
	category_questions=Questions.objects.filter(category=category_)
	#question_votes=QuestionVotes.objects.filter(question=category_questions)

	return render(request,'community_forum/subforums.html',
			{'category':category,
			'category_questions':category_questions,
			
			}
		)

class QuestionView(View):

	def get(self,request,*args,**kwargs):
		question_id=kwargs['pk']
		question=get_object_or_404(Questions,id=question_id)
		answers=Answers.objects.filter(question=question_id)
		#category=Categories.objects.filter(category_name=kwargs['category'])
		context={
			'question':question,
			'answers':answers,
			
		}
		return render(request,'community_forum/questions.html',context)


class AnswerView(LoginRequiredMixin,CreateView):

	model=Answers
	form_class=AnswerForm
	success_url='/community_forum/'
	
	def form_valid(self,form):
		
		
		question_=get_object_or_404(Questions,pk=self.kwargs['pk'])
		category_=get_object_or_404(Categories,category_name=question_.category.category_name)
		obj=form.save(commit=False)
		obj.user=self.request.user.profile
		obj.category=category_
		obj.question=question_
		obj.save()
		subject='New message'
		from_email=settings.EMAIL_HOST_USER
		to_email=obj.user.email_id
		text_content="Hi, somebody answered your question.Login to see!"
		html_content=get_template("community_forum/answered_email.html").render()
		msg= EmailMultiAlternatives(subject,text_content,from_email,[to_email])
		msg.attach_alternative(html_content, "text/html")
		msg.send()

		return super().form_valid(form)
		#return self.render_to_response(self.get_context_data(form=form))
		

class NewQuestionView(LoginRequiredMixin,CreateView):

	model=Questions
	form_class=QuestionForm
	success_url='/community_forum/'
	
	def form_valid(self,form):
		
		category_=get_object_or_404(Categories,category_name=self.kwargs['category'])
		obj=form.save(commit=False)
		obj.user=self.request.user.profile
		obj.category=category_
		obj.save()
		return super().form_valid(form)
	

def QuestionUpVoteView(request,*args,**kwargs):
	question=get_object_or_404(Questions,id=request.POST.get('question_id_up'))
	question.up_votes.add(request.user.profile)
	return HttpResponseRedirect(reverse('community_forum:question-detail',args=[int(kwargs['pk'])]))

def QuestionDownVoteView(request,*args,**kwargs):
	question=get_object_or_404(Questions,id=request.POST.get('question_id_down'))
	question.down_votes.add(request.user.profile)
	return HttpResponseRedirect(reverse('community_forum:question-detail',args=[int(kwargs['pk'])]))


def AnswerUpVoteView(request,*args,**kwargs):
	answer=get_object_or_404(Answers,id=request.POST.get('answer_id_up'))
	answer.up_votes.add(request.user.profile)
	return HttpResponseRedirect(reverse('community_forum:question-detail',args=[int(kwargs['pk_alt'])]))

def AnswerDownVoteView(request,*args,**kwargs):
	answer=get_object_or_404(Answers,id=request.POST.get('answer_id_down'))
	answer.down_votes.add(request.user.profile)
	return HttpResponseRedirect(reverse('community_forum:question-detail',args=[int(kwargs['pk_alt'])]))


def CategoryInfo(request,*args,**kwargs):
	category=get_object_or_404(Categories,id=kwargs['pk'])
	context={
		'category':category
	}
	return render(request,'community_forum/info.html',context)

community_forum/templates/community_forum/answer_update.html
{% block content %}
{% include 'Ask_the_doctor/base.html' %}
<style type="text/css">
	body{
		background-color: #EEEEE0;
	}


	.inner-box{
		margin-top: 1rem;
		margin-bottom: 1rem;

		
	}
	.mic{
		color: #000000;
		font-size: 1.5rem;
	}
	.mic:hover{
		color: blue;

	}
	.re{
		background-color: none;
		border: none;
	}

</style>
<br><br>

<div class="container">
	
	<div class="row">
		<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 inner-box">
					<div class="form-group">
						<form method="POST">
							
							{% csrf_token %}
							{{ form.text | safe }}
							{{ form.media }}
							{{form.as_p}}
							&nbsp;<button type="button" onclick="record1()" class="re"><i class="fas fa-microphone mic"></i></button>
							<p id="instructions">Press the mic to speak</p>
							<br><br>
							<input type="submit" class="btn btn-primary" name="Submit">
							
						</form>
					</div>
				</div>
			</div>
		</div>
		<br><br>

	</div>
</div>

<script type="text/javascript">

		var speechRecognition=window.webkitSpeechRecognition
		var recognition=new speechRecognition()
		var textbox=$("#id_answer")
		var instructions=$("#instructions")
		var content=''
		recognition.continuous=true

		recognition.onstart=function(){
			instructions.text("Voice recognition is on")
		}

		recognition.onspeechend=function(){
			instructions.text("No activity")
		}
		recognition.onerror=function(){
			instructions.text("Try again")
		}

		recognition.onresult=function(event){
			var current=event.resultIndex;
			var transcript=event.results[current][0].transcript;
			console.log(transcript);
			content+=transcript
			CKEDITOR.instances.id_answer.setData(content)
		}

		function record1(event){
			if(content.length){
				content+=''
			}
			recognition.start();
		}
		textbox.on('input',function(){
			content=$(this).val()
		})

	
</script>

{% endblock %}

community_forum/templates/community_forum/answered_email.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h2>Safe space</h2>
<p>Hi, some one has answered your question. Login to see! </p>
	
</body>
</html>

community_forum/templates/community_forum/answers_form.html
{% block content %}
{% include 'ask_the_doctor/base.html' %}
<style type="text/css">
	body{
		background-color: #EEEEE0;
	}


	.inner-box{
		margin-top: 1rem;
		margin-bottom: 1rem;

		
	}
	.mic{
		color: #000000;
		font-size: 1.5rem;
	}
	.mic:hover{
		color: blue;

	}
	.re{
		background-color: none;
		border: none;
	}

</style>
<br><br>

<div class="container">
	
	<div class="row">
		<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 inner-box">
					<div class="form-group">
						<form method="POST">
							
							{% csrf_token %}
							{{ form.text | safe }}
							{{ form.media }}
							{{form.answer.label}}
							{{form.answer}}<br><br>
							&nbsp;<button type="button" onclick="record1()" class="re"><i class="fas fa-microphone mic"></i></button>
							<p id="instructions">Press the mic to speak</p>
							<br><br>

							<input type="submit" class="btn btn-primary" name="Submit">
							
						</form>
					</div>
				</div>
			</div>
		</div>
		<br><br>

	</div>
</div>

<script type="text/javascript">

		var speechRecognition=window.webkitSpeechRecognition
		var recognition=new speechRecognition()
		var textbox=$("#id_answer")
		var instructions=$("#instructions")
		var content=''
		recognition.continuous=true

		recognition.onstart=function(){
			instructions.text("Voice recognition is on")
		}

		recognition.onspeechend=function(){
			instructions.text("No activity")
		}
		recognition.onerror=function(){
			instructions.text("Try again")
		}

		recognition.onresult=function(event){
			var current=event.resultIndex;
			var transcript=event.results[current][0].transcript;
			console.log(transcript);
			content+=transcript
			CKEDITOR.instances.id_answer.setData(content)
		}

		function record1(event){
			if(content.length){
				content+=''
			}
			recognition.start();
		}
		textbox.on('input',function(){
			content=$(this).val()
		})

	
</script>

{% endblock %}

community_forum/templates/community_forum/question_update.html
{% block content %}
{% include 'Ask_the_doctor/base.html' %}
<style type="text/css">
	body{
		background-color: #EEEEE0;
	}


	.inner-box{
		margin-top: 1rem;
		margin-bottom: 1rem;

		
	}
	.mic{
		color: #000000;
		font-size: 1.5rem;
	}
	.mic:hover{
		color: blue;

	}
	.re{
		background-color: none;
		border: none;
	}

</style>
<br><br>

<div class="container">
	
	<div class="row">
		<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 inner-box">
					<div class="form-group">
						<form method="POST">
							
							{% csrf_token %}
							{{ form.text | safe }}
							{{ form.media }}
							{{form.as_p}}
							&nbsp;<button type="button" onclick="record1()" class="re"><i class="fas fa-microphone mic"></i></button>
							<p id="instructions">Press the mic to speak</p>
							<br><br><br><br>
							<input type="submit" class="btn btn-primary" name="Submit">
							
						</form>
					</div>
				</div>
			</div>
		</div>
		<br><br>

	</div>
</div>

<script type="text/javascript">

		var speechRecognition=window.webkitSpeechRecognition
		var recognition=new speechRecognition()
		var textbox=$("#id_question_detail")
		var instructions=$("#instructions")
		var content=''
		recognition.continuous=true

		recognition.onstart=function(){
			instructions.text("Voice recognition is on")
		}

		recognition.onspeechend=function(){
			instructions.text("No activity")
		}
		recognition.onerror=function(){
			instructions.text("Try again")
		}

		recognition.onresult=function(event){
			var current=event.resultIndex;
			var transcript=event.results[current][0].transcript;
			console.log(transcript);
			content+=transcript
			CKEDITOR.instances.id_question_detail.setData(content)
		}

		function record1(event){
			if(content.length){
				content+=''
			}
			recognition.start();
		}
		textbox.on('input',function(){
			content=$(this).val()
		})

	
</script>

{% endblock %}

community_forum/templates/community_forum/questions.html
{% extends 'ask_the_doctor/base.html' %}
{% block content %}

<style type="text/css">
	body{
		background-color: #EEEEE0;
	}
	.up-votes{
		font-size: 2rem;
	}
	.down-votes{
		font-size: 2rem;
	}
	.btn{
		background-color: none;
		border:none;
	}
	.up-votes:hover{
		color: green;
	}
	.down-votes:hover{
		color: red;
	}
	#play_button{
		background-color: white;
		border:none;

	}


</style>
<br><br>


<div class="container" style="background-color:white;">
	<div class="row">
	
		
	

		<div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
			<form action="{% url 'community_forum:up_vote' question.pk %}" method="POST">
				{% csrf_token %}
				<button type="submit" name="question_id_up" value="{{question.id}}" class="btn"><i class="fas fa-long-arrow-alt-up up-votes"></i></button>
			</form>
			&nbsp;&nbsp;&nbsp;{{question.total_upvotes}}<br><br>
			<form action="{% url 'community_forum:down_vote' question.pk %}" method="POST">
				{% csrf_token %}
				<button type="submit" name="question_id_down" value="{{question.id}}" class="btn"><i class="fas fa-long-arrow-alt-down down-votes"></i></button>
			</form>
			&nbsp;&nbsp;&nbsp;{{question.total_downvotes}}
			
			
			
		</div>

	    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
	    	<span style="font-weight: bolder;"><input type="text" id="titleText" hidden="True">{{question.question_title|safe}}</input></span><br><br>
	    	{{question.question_detail|safe}}<br>
	    	<span style="color: blue;">{{question.user.user_name}}</span><br>
	    	<span style="font-size: 0.9rem;color: grey;">{{question.date}}</span><br><br>

	    </div>
	  
	   <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
	   		<br><br><button type="button" id="play_button" onclick="speakQuestion()"><i class="fas fa-volume-up"></i></button>
	   </div>

	    <div class="container">
			<span style="font-weight: bold;"><a href="/community_forum/questions/{{question.id}}/answer/">Answer this question!</a></span>
		</div>

	


	    <br>
	</div>
	<hr>
	<br>
	<div class="row">
	   
	    {% for answers in answers %}

	    <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
			<form action="{% url 'community_forum:answer_up_vote' answers.pk question.pk %}" method="POST">
				{% csrf_token %}
				<button type="submit" name="answer_id_up" value="{{answers.id}}" class="btn"><i class="fas fa-long-arrow-alt-up up-votes"></i></button>
			</form>
			&nbsp;&nbsp;&nbsp;{{answers.total_upvotes}}<br><br>
			<form action="{% url 'community_forum:answer_down_vote' answers.pk question.pk %}" method="POST">
				{% csrf_token %}
				<button type="submit" name="answer_id_down" value="{{answers.id}}" class="btn"><i class="fas fa-long-arrow-alt-down down-votes"></i></button>
			</form>
			&nbsp;&nbsp;&nbsp;{{answers.total_downvotes}}
					
		</div>

	    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 ">
	    	<p>{{answers.answer|safe}}</p><br>
	    	<span style="color: blue;">{{answers.user.user_name}}</span><br>
	    	<span style="font-size: 0.9rem;color: grey;">{{answers.date}}</span><br><hr>
	    </div>

	    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
	    	<br><br><button type="button" id="play_button" onclick="speakAnswer()"><i class="fas fa-volume-up"></i></button>
	    </div>

	    
	    {% endfor %}
	   
	</div>
</div>

<br>
<script type="text/javascript">
	//var msgText=CKEDITOR.instance.id_question_detail.getData();
	
	function speakQuestion(){
		let titleText=document.getElementById("title_text").value;
		var msg = new SpeechSynthesisUtterance();
		//var voices = window.speechSynthesis.getVoices();
		//msg.voice = voices[1]; 
		//msg.voiceURI = 'native';
		msg.volume = 1; // 0 to 1
		msg.rate = 1; // 0.1 to 10
		msg.pitch = 1; //0 to 2
		msg.lang = 'en-IN';
		
		msg.text = titleText

		msg.onend = function(e) {
  			console.log('Finished in ' + event.elapsedTime + ' seconds.');
		};
		window.speechSynthesis.speak(msg);
	}

	function speakAnswer(){
		var msg = new SpeechSynthesisUtterance();
		//var voices = window.speechSynthesis.getVoices();
		//msg.voice = voices[1]; 
		//msg.voiceURI = 'native';
		msg.volume = 1; // 0 to 1
		msg.rate = 1; // 0.1 to 10
		msg.pitch = 1; //0 to 2
		msg.lang = 'en-US';
		var msgText=document.getElementById("id_answer");
		msg.text = msgText;

		msg.onend = function(e) {
  			console.log('Finished in ' + event.elapsedTime + ' seconds.');
		};
		window.speechSynthesis.speak(msg);
	}
                
</script>


{% endblock %}

community_forum/templates/community_forum/questions_form.html
{% block content %}
{% include 'ask_the_doctor/base.html' %}
<style type="text/css">
	body{
		background-color: #EEEEE0;
	}


	.inner-box{
		margin-top: 1rem;
		margin-bottom: 1rem;

		
	}
	.mic{
		color: #000000;
		font-size: 1.5rem;
	}
	.mic:hover{
		color: blue;

	}
	.re{
		background-color: none;
		border: none;
	}

</style>
<br><br>

<div class="container">
	
	<div class="row">
		<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 inner-box">
					<div class="form-group">
						<form method="POST">
							
							{% csrf_token %}
							
								{{ form.text | safe }}
								{{ form.media }}
								{{form.question_title.label}}<br><br>
								<p id="title_text">
									{{form.question_title}}
								</p>
								<br><br>
								
								{{form.question_detail.label}}<br><br>
								<p id="detail_text">
									{{form.question_detail}}
								</p>
								<br><br>
							
							<button type="button" onclick="record1()" class="re"><i class="fas fa-microphone mic"></i></button>
							<p id="instructions">Press the mic to speak</p>
							<br><br>

							<input type="submit" class="btn btn-primary" name="Submit">
							
						</form>
					</div>
				</div>
			</div>
		</div>
		<br><br>

	</div>
</div>

<script type="text/javascript">

		var speechRecognition=window.webkitSpeechRecognition
		var recognition=new speechRecognition()
		var textbox=$("#id_question_detail")
		var instructions=$("#instructions")
		var content=''
		recognition.continuous=true

		recognition.onstart=function(){
			instructions.text("Voice recognition is on")
		}

		recognition.onspeechend=function(){
			instructions.text("No activity")
		}
		recognition.onerror=function(){
			instructions.text("Try again")
		}

		recognition.onresult=function(event){
			var current=event.resultIndex;
			var transcript=event.results[current][0].transcript;
			console.log(transcript);
			content+=transcript
			CKEDITOR.instances.id_question_detail.setData(content)
		}

		function record1(event){
			if(content.length){
				content+=''
			}
			recognition.start();
		}
		textbox.on('input',function(){
			content=$(this).val()
		})

	
</script>
 

{% endblock %}

community_forum/templates/community_forum/subforums.html
{% block content %}
{% include 'ask_the_doctor/base.html' %}
<style type="text/css">
	body{
		background-color: #EEEEE0;
	}
	.cats{
		background-color: white;
	}
</style>
{% if category %}
<br><br>

<div class="container">
	<div class="row">
		<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
			<h3>{{category}}</h3>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
			<span style="font-weight: bolder;font-size: 1.5rem;"><a href="/community_forum/{{category}}/questions/new/">Ask a question</a></span>

		</div>
			
	</div>
	<hr><br>
</div>

<br><br>

<div class="container cats">
	<br>
	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-6 offset-lg-8">
			<b>Up votes</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Down votes</b>
		</div>
		
	</div>
	<div class="row">
		{% for question in category_questions %}
			<br>

			<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
				<a href="/community_forum/questions/{{question.id}}/">{{question.question_title}}</a><br><br>
			</div>
			
			<div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
				
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{question.total_upvotes}}
			</div>
			<div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
				{{question.total_downvotes}}
			</div>
			
			{% empty %}
			<div class="container" style="text-align: center;">
				<p>Sorry! There are no questions in this forum</p>
			</div>

		{% endfor %}

		</div>
	</div>
			
{% else %}
Sorry this page does not exist
{% endif %}

{% endblock %}