Ask_the_doctor/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
app_name="Ask_the_doctor"
urlpatterns=[
	path('',views.TherapistView.as_view()),
	
	path('ask/<int:pk>/',views.NewQuestionView.as_view(), name="ask"),
	path('my_questions/<int:pk>/',views.MyQuestions.as_view()),
	path('my_questions/<int:pk>/edit/',views.QuestionUpdateView),
	#path('search/',views.search_bar,name='search'),




]

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    
	path("home/", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    
   	path('reset_password/',
	auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html",email_template_name = 'accounts/password_reset_email.html'),
	name="password_reset"),

    path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
    name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
    name="password_reset_confirm"),

    path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
    name="password_reset_complete"),

    path('therapist_signup/',views.therapist_signup,name="therapist_signup")

]

safe_space/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('ask_the_doctor/',include('Ask_the_doctor.urls')),
    path('community_forum/',include('community_forum.urls')),
    path('profile/',include('user_profile.urls')),
    path('therapist_dashboard/',include('therapist_dashboard.urls')),
    path('private_chats/',include('private_chats.urls')),
]

Ask_the_doctor/models.py
from django.db import models
from accounts.models import Profile
from accounts.models import Therapist
from ckeditor.fields import RichTextField

# Create your models here.

class question_to_therapist(models.Model):
	class Meta:
		verbose_name_plural="Questions for therapists"

	id=models.AutoField(primary_key=True,unique=True)
	user=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='questionfortherapist',blank=True,null=True)
	therapist=models.ForeignKey(Therapist,on_delete=models.CASCADE,related_name='questionfortherapist',blank=True,null=True)
	question=RichTextField(blank=True,null=True)
	date=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.id} "

	
class answers_from_therapist(models.Model):
	class Meta:
		verbose_name_plural="Answers from therapist"

	id=models.AutoField(primary_key=True,unique=True)
	user=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='answersfromtherapist',blank=True,null=True)
	therapist=models.ForeignKey(Therapist,on_delete=models.CASCADE,related_name='answersfromtherapist',blank=True,null=True)
	question=models.ForeignKey(question_to_therapist,on_delete=models.CASCADE,related_name='answersfromtherapist',blank=True,null=True)
	answer=RichTextField(blank=True,null=True)
	date=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.id} "

Ask_the_doctor/forms.py
from django import forms
from django.forms import ModelForm
from .models import question_to_therapist
from ckeditor.widgets import CKEditorWidget
#from therapist_dashboard.models import Patients
class QuestionForm(forms.ModelForm):
    
	question=forms.CharField(widget=CKEditorWidget(attrs={'class': 'form-control','placeholder': 'Type here'}))

	class Meta:
		model=question_to_therapist
		fields=['question']
		'''widgets={

	    		'question':forms.Textarea(attrs={'class':'form-control','label':'question','placeholder': 'Type here...'})
	    	}'''

   
class QuestionUpdateForm(forms.ModelForm):
	question=forms.CharField(widget=CKEditorWidget(attrs={'class':'form-control','placeholder':'Type here'}))
	class Meta:
		model=question_to_therapist
		fields=['question']

'''class PatientForm(forms.ModelForm):
	name=forms.CharField(widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder':'Enter your name',
		'size':'40'
		}))

	address=forms.CharField(widget=forms.Textarea(attrs={
		'class':'form-control',
		'placeholder':'Enter your address',
		'rows':'2',
		'cols':'70'
		}))
	mental_illness=forms.CharField(widget=forms.TextInput(attrs={
		'class':'form-control',
		'placeholder':'Enter the name of the mental illness you are suffering from. If you do not know, type "Do not know"',
		'size':'40'
		}))

	date_of_birth = forms.DateField(label='Enter your date of birth',widget=forms.DateTimeInput(attrs=
		{'placeholder': 'YYYY-MM-DD',
		'size':'40',
		'class':'datetime-input'
		}))
	gender_choices=[
		('MALE','Male'),
		('FEMALE','Female'),
		('OTHERS','Others'),
		('NOTDISCLOSE','I do not wish to disclose')

	]
	gender=forms.CharField(max_length=2,widget=forms.Select(choices=gender_choices))

	class Meta:
		model=Patients
		fields=['name','gender','date_of_birth','address','mental_illness']
'''

Ask_the_doctor/views.py
from django.shortcuts import render,reverse,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.views import View
from accounts.models import Therapist
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import QuestionForm,QuestionUpdateForm
from django.shortcuts import get_object_or_404
from django.views.generic import ListView,DetailView,CreateView
from .models import question_to_therapist,answers_from_therapist
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
#from .forms import PatientForm
from django.core.mail import send_mail,EmailMultiAlternatives
from django.conf import settings
from django.template.loader import get_template

from community_forum.models import Questions

'''
@login_required
def PatientRegistrationView(request,*args,**kwargs):
	form=PatientForm
	if request.method=='POST':
		form=PatientForm(request.POST)
		if form.is_valid():
			user_=get_object_or_404(Profile,id=request.user.profile.id)
			therapist_= get_object_or_404(Therapist, pk=kwargs['pk'])
			patient=form.save(commit=False)
			patient.user=user_
			patient.therapist=therapist_
			patient.save()
			form.save_m2m()
			return redirect("Ask_the_doctor:ask",id=therapist_.id)
		else:
			form=PatientForm()
	else:
		form=PatientForm()

	context={
	'form':form
	}
    
	return render(request,'Ask_the_doctor/patientform.html',context)
'''
class TherapistView(LoginRequiredMixin,View):

	def get(self, request, *args, **kwargs):

		therapists=Therapist.objects.all()
		context={
			'therapists':therapists
		}
		return render(request,'Ask_the_doctor/ask_the_doctor.html',context)



class NewQuestionView(LoginRequiredMixin,CreateView):
	
	model=question_to_therapist
	form_class=QuestionForm
	#success_url='NewQuestionView'
	
	def get_queryset(self):
		self.therapist = get_object_or_404(Therapist, pk=self.kwargs['pk'])
		return Therapist.objects.filter(pk=self.therapist)

	
	def form_valid(self,form):
		therapist_= get_object_or_404(Therapist, pk=self.kwargs['pk'])
		obj=form.save(commit=False)
		obj.user=self.request.user.profile
		obj.therapist=therapist_
		obj.save()
		subject='New message'
		from_email=settings.EMAIL_HOST_USER
		to_email=therapist_.therapist_email
		text_content="Hi, you have a new message!"
		html_content=get_template("private_chats/msg_received_email.html").render()
		msg= EmailMultiAlternatives(subject,text_content,from_email,[to_email])
		msg.attach_alternative(html_content, "text/html")
		msg.send()

		#return self.render_to_response(self.form_valid(form))
		return self.render_to_response(self.get_context_data(form=form))
		#return super().form_valid(form)


	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		user_=self.request.user.profile
		context["questions"] = question_to_therapist.objects.filter(user=user_).order_by('id')

		return context

	'''def get(self,request,*args,**kwargs):
		return render(request,'ask_the_doctor/ask.html')

	def post(self,request,*args,**kwargs):

		questionform = QuestionForm(request.POST)
		
		therapist_ = get_object_or_404(Therapist, pk=self.kwargs.get('pk'))
		if questionform.is_valid():
			question = questionform.save(commit=False)
			question.user = request.user.profile
			question.therapist=therapist_
			
			question.question=questionform.cleaned_data.get('question')

			question.save()
			return render(request,'ask_the_doctor/ask.html',{'form' :questionform})
			#return render('ask_the_doctor/ask/<int:pk>/')

		return render(request,'ask_the_doctor/')
	'''

class MyQuestions(LoginRequiredMixin,View):

	def get(self,request,*args,**kwargs):
		question_id=kwargs['pk']
		question=question_to_therapist.objects.filter(id=question_id)
		answers=answers_from_therapist.objects.filter(question=question_id)
		context={
			'question':question,
			'answers':answers
		}
		return render(request,'Ask_the_doctor/my_questions.html',context)



@login_required
def QuestionUpdateView(request,*args,**kwargs):
	context={}
	question_id=kwargs['pk']
	#answer_id=kwargs['pk_alt']
	obj=get_object_or_404(question_to_therapist,id=question_id)
	form=QuestionUpdateForm(request.POST or None,instance=obj)
	if form.is_valid():
		form.save()
		#redirect_url=reverse('therapibvst_dashboard:AnswerView',args=[question_id])
		return redirect('/ask_the_doctor/')
	context["form"]=form
	return render(request,'Ask_the_doctor/question_update.html',context)

'''
@login_required
def search_bar(request,*args,**kwargs):
	
    if request.method=='GET':
           
        search_query = request.GET.get('to', None)
        if search_query:
            question_list = Questions.objects.filter(title__icontains=search_query)

   
            context={   
            
            'question_list':question_list
           
            }
        
    return render(request, "Ask_the_doctor/base.html",context)
'''

Ask_the_doctor/templates/Ask_the_doctor/ask_the_doctor.html
{% extends 'ask_the_doctor/base.html' %}
{% block content %}

<style type="text/css">
	.therapist-card{
		box-shadow: 3px;
		background-color: #EED5B7;
	}
	.ask-button{
		border-radius: 50%;
		background-color: green;
	}
</style>

<br><br>
<div class="container">
	<div class="row">
	{% for therapist in therapists %}
	    
	    <div class="col-md-4 d-flex align-items-stretch">
	        <div class="card mb-2 therapist-card mt-3">
	            
	            <div class="card-body">
	                <h5 class="card-title">Dr. {{ therapist.therapist_name }}&nbsp;&nbsp;&nbsp; 
	                

	                	<a class="btn btn-primary ask-button" href="/ask_the_doctor/ask/{{therapist.id}}/">ASK</a></h5>

	                	

	                <p class="card-text"><br> Has a {{ therapist.qualification }} and is a specialist in {{therapist.specialization_area}}. <br>
	                	Office address:<br>
	                	{{therapist.office_address}}<br>
	                
	                	</p>
	            </div>
	        </div>

	    </div>
	    {% endfor %}
	</div>
</div>
{% endblock %}

Ask_the_doctor/templates/Ask_the_doctor/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://use.fontawesome.com/bf6344f959.js"></script>
    <script src="https://kit.fontawesome.com/90d9f37468.js" crossorigin="anonymous"></script>
    <title>{% block title %}Safe space{% endblock %}</title>
     <style type="text/css">
     
      .nav-styles{
        background-color: #FFDAB9;

      }
      .list-styles{
        color:black;
        font-size: 1.2rem;
        font-weight: bold;

      }
      .nav-item a{
        color: #000000 !important;
      }
      .nav-item a:hover{
        color:  #D2691E !important;
      }
       .nav-item a:active{
        color: blue !important;
      }


    </style>
  </head>
  <body>
    <header>
          
  
      <nav class="navbar navbar-expand-lg fixed-top sticky-top nav-styles">
      <a class="navbar-brand" href="#" style="font-size: 1.99rem;font-weight: bolder;color:#A52A2A;font-family: Comic Sans MS, cursive, sans-serif;">Safe space</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" style="background-color:#D2691E ;"></span>
      </button>

      <div class="collapse navbar-collapse list-styles" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/accounts/home/">Home <span class="sr-only">(current)</span></a>
          </li>

          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/ask_the_doctor/">Ask the Doctor</a>
            </li>
          {% else %}
            <span data-toggle="tooltip" data-placement="bottom" title="Please login first">
            <li class="nav-item">
            
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true" style="">Ask the Doctor</a>

            </li>
          </span>

          {% endif %}


          <li class="nav-item">
            <a class="nav-link" href="/community_forum/">Community Forum</a>
          </li>

          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/private_chats/{{request.user.username}}/">Chats</a>
            </li>
          {% else %}
            <span data-toggle="tooltip" data-placement="bottom" title="Please login first">
            <li class="nav-item">
              
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true" style="">Chats</a>
               
            </li>
          </span>


          {% endif %}



          {% if request.user.is_authenticated %}

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{request.user.username}}
              </a>

              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/profile/my_questions">My Questions</a>
                <a class="dropdown-item" href="/profile/my_answers/">My Answers</a>
                <a class="dropdown-item" href="/profile/">Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/accounts/logout/">Logout</a>
              </div>
            </li>

     

     

          {% else %}
            <li class="nav-item">
              <a class="nav-link btn" href="/accounts/login/" style="background-color:#D2691E;color:white !important;height: 2.5rem;width: 6rem;">Login</a>
            </li>
          {% endif %}

          
        </ul>
       <!-- <form class="form-inline my-2 my-lg-0" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Search questions" aria-label="Search" style="width: 18rem;">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </nav>

   
  </header>


  
  

    <main>
      {% block content %}
      {% endblock %}
    </main>

     <script>
      $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();   
      });
    </script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>
</html>

Ask_the_doctor/templates/Ask_the_doctor/my_questions.html
{% extends 'ask_the_doctor/base.html' %}
{% block content %}

<style type="text/css">
	body{
		background-color: #EEEEE0;
	}

	}

</style>
<br><br>
<div class="container" style="background-color:white;">
	<div class="row">

		
		{% for question in question %}
		
	    <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
	    	<span style="font-weight: bolder;">{{question.question|safe}}</span><br>
	    	{{question.user.first_name}} &nbsp;{{question.user.last_name}}<br>
	    	{{question.date}}<hr>

	    </div>
	    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
	    	<br><br><b><a href="/ask_the_doctor/my_questions/{{question.id}}/edit/">Edit</a></b>
	    </div>
	    {% endfor %}
	    <br>
	</div>
	<br>
	<div class="row">
	   
	    {% for answers in answers %}
	    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 ">
	    	<p>{{answers.answer|safe}}</p><br>
	    	{{answers.therapist.therapist_name}}<br>
	    	{{answers.date}}<br><hr>
	    </div>
	    {% endfor %}
	    
	</div>
</div>





{% endblock %}

Ask_the_doctor/templates/Ask_the_doctor/question_to_therapist_form.html
{% extends 'Ask_the_doctor/base.html' %}
{% block content %}

<style type="text/css">
	body{
		background-color: #EEEEE0;

	}
	

		
	
	.mic{
		color: #000000;
		font-size: 1.5rem;
	}
	.mic:hover{
		color: blue;

	}
	.question_card{
		box-shadow: 3px;
		background-color: #EED5B7;
	}
	.flip {
	  font-size:1rem;
	  color: blue;
	}

	.card-text {

	  display: none;
	}
	.re{
		background-color: none;
		border: none;
	}
</style>
<br><br>

	<div class="container" style="background-color: white;">
		<div class="row">
			<br>
				<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 inner-box">
					<div class="form-group">
						<form method="POST">
							<p>
							{% csrf_token %}
							{{ form.text | safe }}
							{{ form.media }}
							{% for field in form %}
								{{field.label}}<span style="color: red;font-size: 1.2rem;">*</span><br>

								{{field}}
								{% if field.errors %}
									{% for error in field.errors %}
						                <p style="color: blue">{{ error }}</p>
						             {% endfor %}
						        {% endif %}

							{% endfor %}
							</p>
							&nbsp;<button type="button" onclick="record1()" class="re"><i class="fas fa-microphone mic"></i></button>
							<p id="instructions">Press the mic to speak</p>
							<br><br>
							<input type="submit" class="btn btn-primary" name="Submit">
							
						</form>
					</div>
				</div>
		
		
		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
		Your other questions <br><br>
	
			
				{% for questions in questions %}
				
                <a href="/ask_the_doctor/my_questions/{{questions.id}}" class="card-title flip">{{questions.question|safe}}</a>
                
    	
				{% endfor %}
		</div>
		</div>
		</div>
		


<!--<script>
function flipFunction() {
  //var question=document.getElementsByClassName('card-text')
   var question =document.querySelectorAll(".card-text");
  
 
  	for(var i=0;i<question.length;i+=1)
  	{
  		if(question[i].style.display==="none")
		{
			question[i].style.display="block";	
		}
		else
		{
			question[i].style.display="none";
		}
  		
  	}
 

}
</script>
-->

<!---<div class="container">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 offset-lg-3 offset-md-3 outer-box">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 inner-box">
				<form method="POST">
					{% csrf_token %}

					<label style="font-size: 1.5rem;font-weight: bolder;">Ask a question</label><br>
					<input type="text" name="title" style="width: 32rem;height: 3rem;border-radius: 6px;" placeholder="Write a title..."></input><br>
					<label><b>Elaborate</b></label>
					<textarea rows="6" cols="68" type="textarea" placeholder="Type here..." name="detail" style="border-radius: 6px;"></textarea><br><br>
					&nbsp;<a href="/"><i class="fas fa-microphone mic"></i></a>
					<div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 offset-lg-10 offset-md-10">
						<input type="submit" class="btn btn-primary" name="Submit">
					</div>
				</form>
			</div>

		</div>
	</div>
</div>-->

<script type="text/javascript">

		var speechRecognition=window.webkitSpeechRecognition
		var recognition=new speechRecognition()
		var textbox=$("#id_question")
		var instructions=$("#instructions")
		var content=''
		recognition.continuous=true

		recognition.onstart=function(){
			instructions.text("Voice recognition is on")
		}

		recognition.onspeechend=function(){
			instructions.text("No activity")
		}
		recognition.onerror=function(){
			instructions.text("Try again")
		}

		recognition.onresult=function(event){
			var current=event.resultIndex;
			var transcript=event.results[current][0].transcript;
			console.log(transcript);
			content+=transcript
			CKEDITOR.instances.id_question.setData(content)
		}

		function record1(event){
			if(content.length){
				content+=''
			}
			recognition.start();
		}
		textbox.on('input',function(){
			content=$(this).val()
		})

	
</script>

{% endblock %}

Ask_the_doctor/templates/Ask_the_doctor/question_update.html
{% extends 'Ask_the_doctor/base.html' %}
{% block content %}

<style type="text/css">
	body{
		background-color: #EEEEE0;
	}


	.inner-box{
		margin-top: 1rem;
		margin-bottom: 1rem;

		
	}
	.mic{
		color: #000000;
		font-size: 1.5rem;
	}
	.mic:hover{
		color: blue;

	}
	.re{
		background-color: none;
		border: none;
	}

</style>
<br><br>

<div class="container">
	
	<div class="row">
		<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 inner-box">
					<div class="form-group">
						<form method="POST">
							
							{% csrf_token %}
							{{ form.text | safe }}
							{{ form.media }}
							{{form.as_p}}
							&nbsp;<button type="button" onclick="record1()" class="re"><i class="fas fa-microphone mic"></i></button>
							<p id="instructions">Press the mic to speak</p>
							<br><br>
							<input type="submit" class="btn btn-primary" name="Submit">
							
						</form>
					</div>
				</div>
			</div>
		</div>
		<br><br>

	</div>
</div>
<script type="text/javascript">

		var speechRecognition=window.webkitSpeechRecognition
		var recognition=new speechRecognition()
		var textbox=$("#id_question")
		var instructions=$("#instructions")
		var content=''
		recognition.continuous=true

		recognition.onstart=function(){
			instructions.text("Voice recognition is on")
		}

		recognition.onspeechend=function(){
			instructions.text("No activity")
		}
		recognition.onerror=function(){
			instructions.text("Try again")
		}

		recognition.onresult=function(event){
			var current=event.resultIndex;
			var transcript=event.results[current][0].transcript;
			console.log(transcript);
			content+=transcript
			CKEDITOR.instances.id_question.setData(content)
		}

		function record1(event){
			if(content.length){
				content+=''
			}
			recognition.start();
		}
		textbox.on('input',function(){
			content=$(this).val()
		})

	
</script>
{% endblock %}